### ISSUE TITLE
Continues to run after screensaver exits

### ISSUE THREAD

**Issue by socketfork** [robertventurini/FlyingToasters#6]
The screen saver appears to leave a thread behind called "legacyScreenSaver (Wallpaper)" that continues to burn CPU and GPU cycles in the background, even after the screen saver exits.

**Comment by robertventurini** [comment]
Unfortunately this issue is relating to changes in the Apple screensaver system that was introduced with Sonoma. See https://github.com/robertventurini/FlyingToasters/issues/4 for more details.
